title: Igor Net
author: Igor Talankin
email: "italankin@gmail.com"
description: >-
  Android developer writing about stuff
baseurl: ""
url: "https://italankin.me"
google_analytics: G-ZYJ7TFN9RB

theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      category: "general"

permalink: /blog/:title/
header_pages:
  - projects.markdown
  - about.markdown
  - support.markdown

minima:
  social_links:
    github: italankin
    instagram: igortalankin
    stackoverflow: "3604617"
    telegram: italankin
